#Generated by Fabric Compiler ( version 2025.2 <build 211867> ) at Wed Sep 23 20:15:31 2026

add_design "E:/code/PangoWork/Works/i2c/Designs/Driver/i2c/i2c_driver.v" -library work -verilog
add_design "E:/code/PangoWork/Works/i2c/Designs/Hardware/eeprom/eeprom.v" -library work -verilog
add_design "E:/code/PangoWork/Works/i2c/ipcore/eeprom_rx_fifo/eeprom_rx_fifo.idf"
add_design "E:/code/PangoWork/Works/i2c/ipcore/eeprom_tx_fifo/eeprom_tx_fifo.idf"
set_option {max_threads} {0}
set_option -options {top_module	eeprom	top_library	work} [get_filesets design_1]
set_option max_threads 0
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
set_option -options { top_module {eeprom}} [get_filesets design_1]
launch_tasks [get_tasks {syn_1}] -to_action compile
wait_on_tasks [get_tasks {syn_1}] -to_action compile
