#Generated by Fabric Compiler ( version 2025.2 <build 211867> ) at Tue Sep 29 20:00:13 2026

add_design E:/code/PangoWork/Works/flash/ipcore/pll_50mhz/pll_50mhz.idf
add_design E:/code/PangoWork/Works/flash/ipcore/flash_rx_fifo/flash_rx_fifo.idf
add_design E:/code/PangoWork/Works/flash/ipcore/cp2102_tx_fifo/cp2102_tx_fifo.idf
