#Generated by Fabric Compiler ( version 2025.2 <build 211867> ) at Sun Sep 27 17:16:20 2026

add_design "E:/code/PangoWork/Works/hdmi/Designs/hardware/ms7200/ms7200_driver.v" -library work -verilog
set_option -options {top_module	ms7200_driver} [get_filesets design_1]
set_option -options {fsm_compiler	true} [get_actions compile -of_objects [get_tasks syn_1]]
set_option max_threads 0
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
set_option -options { top_module {ms7200_driver}} [get_filesets design_1]
launch_tasks [get_tasks {syn_1}] -to_action compile
wait_on_tasks [get_tasks {syn_1}] -to_action compile
