#Generated by Fabric Compiler ( version 2022.1 <build 99559> ) at Wed Feb  8 18:52:29 2023

set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -fsm_compiler {original} -top_module hdmi_rx_tx
synthesize -dir {C:/pango/PDS_2021.4-SP2/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
synthesize -dir {C:/pango/PDS_2021.4-SP2/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -fsm_compiler {original} -top_module hdmi_rx_tx
synthesize -dir {C:/pango/PDS_2021.4-SP2/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {C:/pango/PDS_2021.4-SP2/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
add_constraint "C:/Users/w/Desktop/MES50HP/2_demo/07_hdmi_loop/src/hdmi_loop.fdc"
remove_constraint  -logic -fdc "C:/Users/w/Desktop/MES50HP/2_demo/07_hdmi_loop/src/hdmi_rx_tx.fdc"
add_design "C:/Users/w/Desktop/MES50HP/2_demo/07_hdmi_loop/src/hdmi_loop.v"
remove_design -verilog "C:/Users/w/Desktop/MES50HP/2_demo/07_hdmi_loop/src/hdmi_rx_tx.v"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -fsm_compiler {original} -top_module hdmi_loop
synthesize -dir {C:/pango/PDS_2021.4-SP2/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -fsm_compiler {original} -top_module hdmi_loop
synthesize -dir {C:/pango/PDS_2021.4-SP2/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -fsm_compiler {original} -top_module hdmi_loop
synthesize -dir {C:/pango/PDS_2021.4-SP2/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -fsm_compiler {original} -top_module hdmi_loop
synthesize -dir {C:/pango/PDS_2021.4-SP2/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -fsm_compiler {original} -top_module hdmi_loop
synthesize -dir {C:/pango/PDS_2021.4-SP2/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -fsm_compiler {original} -top_module hdmi_loop
synthesize -dir {C:/pango/PDS_2021.4-SP2/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -fsm_compiler {original} -top_module hdmi_loop
synthesize -dir {C:/pango/PDS_2021.4-SP2/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -fsm_compiler {original} -top_module hdmi_loop
synthesize -dir {C:/pango/PDS_2021.4-SP2/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_option max_threads 0
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
set_option -options { top_module {hdmi_loop}} [get_filesets design_1]
launch_tasks [get_tasks {syn_1}] -to_action compile
wait_on_tasks [get_tasks {syn_1}] -to_action compile
set_option -options { fsm_encoding {original}} [get_actions synthesize -of_objects [get_tasks syn_1]]
launch_tasks [get_tasks {syn_1}] -to_action synthesize
wait_on_tasks [get_tasks {syn_1}] -to_action synthesize
launch_tasks [get_tasks {pnr_1}] -to_action dev_map
wait_on_tasks [get_tasks {pnr_1}] -to_action dev_map
launch_tasks [get_tasks {pnr_1}] -to_action place
wait_on_tasks [get_tasks {pnr_1}] -to_action place
launch_tasks [get_tasks {pnr_1}] -to_action route
wait_on_tasks [get_tasks {pnr_1}] -to_action route
launch_tasks [get_tasks {pnr_1}] -to_action route_optimize
wait_on_tasks [get_tasks {pnr_1}] -to_action route_optimize
launch_tasks [get_tasks {pnr_1}] -to_action report_timing
wait_on_tasks [get_tasks {pnr_1}] -to_action report_timing
launch_tasks [get_tasks {pnr_1}] -to_action gen_bit_stream
wait_on_tasks [get_tasks {pnr_1}] -to_action gen_bit_stream
set_option max_threads 0
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
set_option -options { top_module {hdmi_loop}} [get_filesets design_1]
launch_tasks [get_tasks {syn_1}] -to_action compile
wait_on_tasks [get_tasks {syn_1}] -to_action compile
