#ifndef BMI088_REG_H
#define BMI088_REG_H
/**
 * @file bmi088reg.h
 * @brief BMI088 register map and configuration values.
 */

/*----- 常用换算系数 -----*/
// #define BMI088_ACCEL_3G_SEN 0.0008974358974f
#define BMI088_ACCEL_3G_SEN 0.00089685f
#define BMI088_ACCEL_6G_SEN (BMI088_ACCEL_3G_SEN * 2.0f)
#define BMI088_ACCEL_12G_SEN (BMI088_ACCEL_3G_SEN * 4.0f)
#define BMI088_ACCEL_24G_SEN 0.0071748f
#define DEG2SEC 0.0174532925f
#define SEC2DEG 57.295779578f
// #define PI 3.14159265f

/*----- 通用位操作 -----*/
#define BMI088_BIT(n) (1U << (n))
#define BMI088_FIELD_PREP(mask, shift, value) (((value) << (shift)) & (mask))

/*----- BMI088 SPI 协议 -----*/
#define BMI088_SPI_WRITE_CODE 0x7F
#define BMI088_SPI_READ_CODE 0x80

/*=====================================================================
 * Accelerometer register map
 *====================================================================*/

/*----- 0x00: ACC_CHIP_ID -----*/
#define ACC_CHIP_ID_ADDR 0x00
#define ACC_CHIP_ID_RESET 0x1E
#define ACC_CHIP_ID_VAL ACC_CHIP_ID_RESET

/*----- 0x02: ACC_ERR_REG -----*/
#define ACC_ERR_REG_ADDR 0x02
#define ACC_ERR_REG_ERROR_CODE_MASK 0x1C
#define ACC_ERR_REG_ERROR_CODE_SHIFT 2
#define ACC_ERR_REG_FATAL_ERR BMI088_BIT(0)
#define ACC_ERR_REG_ERROR_NONE 0x00
#define ACC_ERR_REG_ERROR_ACC_CONF 0x01

/*----- 0x03: ACC_STATUS -----*/
#define ACC_STATUS_ADDR 0x03
#define ACC_STATUS_DRDY BMI088_BIT(7)

/*----- 0x12 - 0x17: ACC data -----*/
#define ACC_X_LSB_ADDR 0x12
#define ACC_X_MSB_ADDR 0x13
#define ACC_Y_LSB_ADDR 0x14
#define ACC_Y_MSB_ADDR 0x15
#define ACC_Z_LSB_ADDR 0x16
#define ACC_Z_MSB_ADDR 0x17
#define ACC_XYZ_LEN 6

/*----- 0x18 - 0x1A: Sensor time -----*/
#define SENSORTIME_0_ADDR 0x18
#define SENSORTIME_1_ADDR 0x19
#define SENSORTIME_2_ADDR 0x1A
#define SENSORTIME_LEN 3
#define SENSORTIME_0_UNIT (39.0625f / 1000000.0f)
#define SENSORTIME_1_UNIT (10.0f / 1000.0f)
#define SENSORTIME_2_UNIT 2.56f
#define SENSORTIME_FULL_SCALE_S 655.36f

/*----- 0x1D: ACC_INT_STAT_1 -----*/
#define ACC_INT_STAT_1_ADDR 0x1D
#define ACC_INT_STAT_1_DRDY BMI088_BIT(7)

/*----- 0x22 - 0x23: Temperature -----*/
#define TEMP_MSB_ADDR 0x22
#define TEMP_LSB_ADDR 0x23
#define TEMP_LEN 2
#define TEMP_UNIT 0.125f
#define TEMP_BIAS 23.0f
#define TEMP_INVALID_MSB 0x80

/*----- 0x24 - 0x25: ACC FIFO_LENGTH -----*/
#define ACC_FIFO_LENGTH_0_ADDR 0x24
#define ACC_FIFO_LENGTH_1_ADDR 0x25
#define ACC_FIFO_LENGTH_LEN 2
#define ACC_FIFO_LENGTH_MASK 0x3FFF
#define ACC_FIFO_EMPTY_VALUE 0x8000

/*----- 0x26: ACC FIFO_DATA -----*/
#define ACC_FIFO_DATA_ADDR 0x26

/*----- 0x40: ACC_CONF -----*/
#define ACC_CONF_ADDR 0x40
#define ACC_CONF_RESET 0xA8
#define ACC_CONF_BWP_MASK 0xF0
#define ACC_CONF_BWP_SHIFT 4
#define ACC_CONF_ODR_MASK 0x0F
#define ACC_CONF_ODR_SHIFT 0

/* Existing code uses ACC_CONF_RESERVED plus the 3-bit filter value. */
#define ACC_CONF_RESERVED 0x01
#define ACC_CONF_BWP_OSR4 0x00
#define ACC_CONF_BWP_OSR2 0x01
#define ACC_CONF_BWP_NORM 0x02
#define ACC_CONF_BWP_OSR4_FIELD 0x08
#define ACC_CONF_BWP_OSR2_FIELD 0x09
#define ACC_CONF_BWP_NORM_FIELD 0x0A
#define ACC_CONF_ODR_RESERVED_0 0x00
#define ACC_CONF_ODR_RESERVED_1 0x01
#define ACC_CONF_ODR_RESERVED_2 0x02
#define ACC_CONF_ODR_RESERVED_3 0x03
#define ACC_CONF_ODR_RESERVED_4 0x04
#define ACC_CONF_ODR_12_5_Hz 0x05
#define ACC_CONF_ODR_25_Hz 0x06
#define ACC_CONF_ODR_50_Hz 0x07
#define ACC_CONF_ODR_100_Hz 0x08
#define ACC_CONF_ODR_200_Hz 0x09
#define ACC_CONF_ODR_400_Hz 0x0A
#define ACC_CONF_ODR_800_Hz 0x0B
#define ACC_CONF_ODR_1600_Hz 0x0C
#define ACC_CONF_VALUE(bwp, odr) ((uint8_t)((ACC_CONF_RESERVED << 7) | ((bwp) << ACC_CONF_BWP_SHIFT) | (odr)))
#define ACC_CONF_FIELD_VALUE(bwp_field, odr) ((uint8_t)(((bwp_field) << ACC_CONF_BWP_SHIFT) | (odr)))

/*----- 0x41: ACC_RANGE -----*/
#define ACC_RANGE_ADDR 0x41
#define ACC_RANGE_RESET 0x01
#define ACC_RANGE_MASK 0x03
#define ACC_RANGE_3G 0x00
#define ACC_RANGE_6G 0x01
#define ACC_RANGE_12G 0x02
#define ACC_RANGE_24G 0x03

/*----- 0x45: ACC FIFO_DOWNS -----*/
#define ACC_FIFO_DOWNS_ADDR 0x45
#define ACC_FIFO_DOWNS_RESERVED_BIT BMI088_BIT(7)
#define ACC_FIFO_DOWNS_MASK 0x70
#define ACC_FIFO_DOWNS_SHIFT 4
#define ACC_FIFO_DOWNS_FACTOR_1 0x00
#define ACC_FIFO_DOWNS_FACTOR_2 0x01
#define ACC_FIFO_DOWNS_FACTOR_4 0x02
#define ACC_FIFO_DOWNS_FACTOR_8 0x03
#define ACC_FIFO_DOWNS_FACTOR_16 0x04
#define ACC_FIFO_DOWNS_FACTOR_32 0x05
#define ACC_FIFO_DOWNS_FACTOR_64 0x06
#define ACC_FIFO_DOWNS_FACTOR_128 0x07
#define ACC_FIFO_DOWNS_VALUE(factor) ((uint8_t)(ACC_FIFO_DOWNS_RESERVED_BIT | ((factor) << ACC_FIFO_DOWNS_SHIFT)))

/*----- 0x46 - 0x47: ACC FIFO_WTM -----*/
#define ACC_FIFO_WTM_0_ADDR 0x46
#define ACC_FIFO_WTM_1_ADDR 0x47
#define ACC_FIFO_WTM_LEN 2
#define ACC_FIFO_WTM_MASK 0x1FFF

/*----- 0x48: ACC FIFO_CONFIG_0 -----*/
#define ACC_FIFO_CONFIG_0_ADDR 0x48
#define ACC_FIFO_CONFIG_0_RESERVED_BIT BMI088_BIT(1)
#define ACC_FIFO_CONFIG_0_MODE_MASK BMI088_BIT(0)
#define ACC_FIFO_CONFIG_0_MODE_STREAM 0x00
#define ACC_FIFO_CONFIG_0_MODE_FIFO 0x01
#define ACC_FIFO_CONFIG_0_VALUE(mode) ((uint8_t)(ACC_FIFO_CONFIG_0_RESERVED_BIT | (mode)))

/*----- 0x49: ACC FIFO_CONFIG_1 -----*/
#define ACC_FIFO_CONFIG_1_ADDR 0x49
#define ACC_FIFO_CONFIG_1_ACC_ENABLE BMI088_BIT(6)
#define ACC_FIFO_CONFIG_1_RESERVED_BIT BMI088_BIT(4)
#define ACC_FIFO_CONFIG_1_INT1_ENABLE BMI088_BIT(3)
#define ACC_FIFO_CONFIG_1_INT2_ENABLE BMI088_BIT(2)
#define ACC_FIFO_CONFIG_1_DISABLED ACC_FIFO_CONFIG_1_RESERVED_BIT
#define ACC_FIFO_CONFIG_1_ACC_ONLY (ACC_FIFO_CONFIG_1_RESERVED_BIT | ACC_FIFO_CONFIG_1_ACC_ENABLE)

/*----- 0x53: INT1_IO_CONF -----*/
#define INT1_IO_CTRL_ADDR 0x53
#define ACC_INT1_IO_INPUT_ENABLE BMI088_BIT(4)
#define ACC_INT1_IO_OUTPUT_ENABLE BMI088_BIT(3)
#define ACC_INT1_IO_PUSH_PULL (0U << 2)
#define ACC_INT1_IO_OPEN_DRAIN BMI088_BIT(2)
#define ACC_INT1_IO_ACTIVE_LOW (0U << 1)
#define ACC_INT1_IO_ACTIVE_HIGH BMI088_BIT(1)
#define ACC_INT1_IO_DISABLED 0x00
#define ACC_INT1_IO_DRDY_OUTPUT (ACC_INT1_IO_OUTPUT_ENABLE | ACC_INT1_IO_PUSH_PULL | ACC_INT1_IO_ACTIVE_HIGH)

/*----- 0x54: INT2_IO_CONF -----*/
#define INT2_IO_CTRL_ADDR 0x54
#define ACC_INT2_IO_INPUT_ENABLE BMI088_BIT(4)
#define ACC_INT2_IO_OUTPUT_ENABLE BMI088_BIT(3)
#define ACC_INT2_IO_PUSH_PULL (0U << 2)
#define ACC_INT2_IO_OPEN_DRAIN BMI088_BIT(2)
#define ACC_INT2_IO_ACTIVE_LOW (0U << 1)
#define ACC_INT2_IO_ACTIVE_HIGH BMI088_BIT(1)
#define ACC_INT2_IO_DISABLED 0x00
#define ACC_INT2_IO_DRDY_OUTPUT (ACC_INT2_IO_OUTPUT_ENABLE | ACC_INT2_IO_PUSH_PULL | ACC_INT2_IO_ACTIVE_HIGH)

/*----- 0x58: INT1_INT2_MAP_DATA -----*/
#define INT_MAP_DATA_ADDR 0x58
#define ACC_INT_MAP_DATA_INT2_DRDY BMI088_BIT(6)
#define ACC_INT_MAP_DATA_INT2_FIFO_WM BMI088_BIT(5)
#define ACC_INT_MAP_DATA_INT2_FIFO_FULL BMI088_BIT(4)
#define ACC_INT_MAP_DATA_INT1_DRDY BMI088_BIT(2)
#define ACC_INT_MAP_DATA_INT1_FIFO_WM BMI088_BIT(1)
#define ACC_INT_MAP_DATA_INT1_FIFO_FULL BMI088_BIT(0)
#define ACC_INT_MAP_DATA_DRDY_TO_INT1 ACC_INT_MAP_DATA_INT1_DRDY
#define ACC_INT_MAP_DATA_DRDY_TO_INT2 ACC_INT_MAP_DATA_INT2_DRDY
#define ACC_INT_MAP_DATA_DRDY_TO_INT1_INT2 (ACC_INT_MAP_DATA_INT1_DRDY | ACC_INT_MAP_DATA_INT2_DRDY)

/*----- 0x6D: ACC_SELF_TEST -----*/
#define ACC_SELF_TEST_ADDR 0x6D
#define ACC_SELF_TEST_OFF 0x00
#define ACC_SELF_TEST_POS 0x0D
#define ACC_SELF_TEST_NEG 0x09

/*----- 0x7C: ACC_PWR_CONF -----*/
#define ACC_PWR_CONF_ADDR 0x7C
#define ACC_PWR_CONF_RESET 0x03
#define ACC_PWR_CONF_SUS 0x03
#define ACC_PWR_CONF_ACT 0x00

/*----- 0x7D: ACC_PWR_CTRL -----*/
#define ACC_PWR_CTRL_ADDR 0x7D
#define ACC_PWR_CTRL_RESET 0x00
#define ACC_PWR_CTRL_ON 0x04
#define ACC_PWR_CTRL_OFF 0x00

/*----- 0x7E: ACC_SOFTRESET -----*/
#define ACC_SOFTRESET_ADDR 0x7E
#define ACC_SOFTRESET_VAL 0xB6

/*=====================================================================
 * Gyroscope register map
 *====================================================================*/

/*----- 0x00: GYRO_CHIP_ID -----*/
#define GYRO_CHIP_ID_ADDR 0x00
#define GYRO_CHIP_ID_RESET 0x0F
#define GYRO_CHIP_ID_VAL GYRO_CHIP_ID_RESET

/*----- 0x02 - 0x07: GYRO rate data -----*/
#define GYRO_RATE_X_LSB_ADDR 0x02
#define GYRO_RATE_X_MSB_ADDR 0x03
#define GYRO_RATE_Y_LSB_ADDR 0x04
#define GYRO_RATE_Y_MSB_ADDR 0x05
#define GYRO_RATE_Z_LSB_ADDR 0x06
#define GYRO_RATE_Z_MSB_ADDR 0x07
#define GYRO_XYZ_LEN 6

/*----- 0x0A: GYRO_INT_STAT_1 -----*/
#define GYRO_INT_STAT_1_ADDR 0x0A
#define GYRO_INT_STAT_1_DRDY BMI088_BIT(7)
#define GYRO_INT_STAT_1_FIFO_INT BMI088_BIT(4)

/*----- 0x0E: GYRO FIFO_STATUS -----*/
#define GYRO_FIFO_STATUS_ADDR 0x0E
#define GYRO_FIFO_STATUS_OVERRUN BMI088_BIT(7)
#define GYRO_FIFO_STATUS_FRAME_COUNTER_MASK 0x7F

/*----- 0x0F: GYRO_RANGE -----*/
#define GYRO_RANGE_ADDR 0x0F
#define GYRO_RANGE_RESET 0x00
#define GYRO_RANGE_2000_DEG_S 0x00
#define GYRO_RANGE_1000_DEG_S 0x01
#define GYRO_RANGE_500_DEG_S 0x02
#define GYRO_RANGE_250_DEG_S 0x03
#define GYRO_RANGE_125_DEG_S 0x04
#define GYRO_RANGE_2000_LSB_PER_DEG_S 16.384f
#define GYRO_RANGE_1000_LSB_PER_DEG_S 32.768f
#define GYRO_RANGE_500_LSB_PER_DEG_S 65.536f
#define GYRO_RANGE_250_LSB_PER_DEG_S 131.072f
#define GYRO_RANGE_125_LSB_PER_DEG_S 262.144f

/*----- 0x10: GYRO_BANDWIDTH -----*/
#define GYRO_BANDWIDTH_ADDR 0x10
#define GYRO_BANDWIDTH_RESET 0x80
#define GYRO_ODR_2000Hz_BANDWIDTH_532Hz 0x00
#define GYRO_ODR_2000Hz_BANDWIDTH_230Hz 0x01
#define GYRO_ODR_1000Hz_BANDWIDTH_116Hz 0x02
#define GYRO_ODR_400Hz_BANDWIDTH_47Hz 0x03
#define GYRO_ODR_200Hz_BANDWIDTH_23Hz 0x04
#define GYRO_ODR_100Hz_BANDWIDTH_12Hz 0x05
#define GYRO_ODR_200Hz_BANDWIDTH_64Hz 0x06
#define GYRO_ODR_100Hz_BANDWIDTH_32Hz 0x07

/*----- 0x11: GYRO_LPM1 -----*/
#define GYRO_LPM1_ADDR 0x11
#define GYRO_LPM1_RESET 0x00
#define GYRO_LPM1_NOR 0x00
#define GYRO_LPM1_NORMAL GYRO_LPM1_NOR
#define GYRO_LPM1_SUS 0x80
#define GYRO_LPM1_SUSPEND GYRO_LPM1_SUS
#define GYRO_LPM1_DEEP_SUS 0x20
#define GYRO_LPM1_DEEP_SUSPEND GYRO_LPM1_DEEP_SUS

/*----- 0x14: GYRO_SOFTRESET -----*/
#define GYRO_SOFTRESET_ADDR 0x14
#define GYRO_SOFTRESET_VAL 0xB6

/*----- 0x15: GYRO_INT_CTRL -----*/
#define GYRO_INT_CTRL_ADDR 0x15
#define GYRO_INT_CTRL_DRDY_ENABLE BMI088_BIT(7)
#define GYRO_INT_CTRL_FIFO_ENABLE BMI088_BIT(6)
#define GYRO_INT_CTRL_DISABLE 0x00

/*----- 0x16: INT3_INT4_IO_CONF -----*/
#define GYRO_INT3_INT4_IO_CONF_ADDR 0x16
#define GYRO_INT3_INT4_IO_DEFAULT 0x0F
#define GYRO_INT4_IO_PUSH_PULL (0U << 3)
#define GYRO_INT4_IO_OPEN_DRAIN BMI088_BIT(3)
#define GYRO_INT4_IO_ACTIVE_LOW (0U << 2)
#define GYRO_INT4_IO_ACTIVE_HIGH BMI088_BIT(2)
#define GYRO_INT3_IO_PUSH_PULL (0U << 1)
#define GYRO_INT3_IO_OPEN_DRAIN BMI088_BIT(1)
#define GYRO_INT3_IO_ACTIVE_LOW (0U << 0)
#define GYRO_INT3_IO_ACTIVE_HIGH BMI088_BIT(0)
#define GYRO_INT3_IO_DRDY_OUTPUT (GYRO_INT3_IO_PUSH_PULL | GYRO_INT3_IO_ACTIVE_HIGH)
#define GYRO_INT4_IO_DRDY_OUTPUT (GYRO_INT4_IO_PUSH_PULL | GYRO_INT4_IO_ACTIVE_HIGH)

/*----- 0x18: INT3_INT4_IO_MAP -----*/
#define GYRO_INT3_INT4_IO_MAP_ADDR 0x18
#define GYRO_INT_MAP_DRDY_TO_INT4 BMI088_BIT(7)
#define GYRO_INT_MAP_FIFO_TO_INT4 BMI088_BIT(6)
#define GYRO_INT_MAP_FIFO_TO_INT3 BMI088_BIT(5)
#define GYRO_INT_MAP_DRDY_TO_INT3 BMI088_BIT(0)
#define GYRO_INT_MAP_DRDY_TO_INT3_INT4 (GYRO_INT_MAP_DRDY_TO_INT3 | GYRO_INT_MAP_DRDY_TO_INT4)

/*----- 0x1E: GYRO FIFO_WM_ENABLE -----*/
#define GYRO_FIFO_WM_ENABLE_ADDR 0x1E
#define GYRO_FIFO_WM_DISABLE 0x08
#define GYRO_FIFO_WM_ENABLE 0x88

/*----- 0x34: GYRO FIFO_EXT_INT_S -----*/
#define GYRO_FIFO_EXT_INT_S_ADDR 0x34
#define GYRO_FIFO_EXT_INT_S_ENABLE BMI088_BIT(5)
#define GYRO_FIFO_EXT_INT_S_SEL_INT3 (0U << 4)
#define GYRO_FIFO_EXT_INT_S_SEL_INT4 BMI088_BIT(4)

/*----- 0x3C: GYRO_SELF_TEST -----*/
#define GYRO_SELF_TEST_ADDR 0x3C
#define GYRO_SELF_TEST_RATE_OK BMI088_BIT(4)
#define GYRO_SELF_TEST_BIST_FAIL BMI088_BIT(2)
#define GYRO_SELF_TEST_BIST_RDY BMI088_BIT(1)
#define GYRO_SELF_TEST_TRIG_BIST BMI088_BIT(0)
#define GYRO_SELF_TEST_ON GYRO_SELF_TEST_TRIG_BIST

/*----- 0x3D: GYRO FIFO_CONFIG_0 -----*/
#define GYRO_FIFO_CONFIG_0_ADDR 0x3D
#define GYRO_FIFO_CONFIG_0_WM_LEVEL_MASK 0x7F

/*----- 0x3E: GYRO FIFO_CONFIG_1 -----*/
#define GYRO_FIFO_CONFIG_1_ADDR 0x3E
#define GYRO_FIFO_CONFIG_1_MODE_FIFO 0x40
#define GYRO_FIFO_CONFIG_1_MODE_STREAM 0x80
#define GYRO_FIFO_CONFIG_1_MODE_RESERVED 0x00

/*----- 0x3F: GYRO FIFO_DATA -----*/
#define GYRO_FIFO_DATA_ADDR 0x3F

#endif // BMI088_REG_H