#Generated by Fabric Compiler ( version 2022.2-SP6.7.1 <build 188940> ) at Wed Jun 17 10:52:57 2026

add_design "E:/FPGA_pro/Pango/PG2L100H/29_eeprom_byte_rd_wr/rtl/eeprom_byte_rd_wr.v"
add_design "E:/FPGA_pro/Pango/PG2L100H/29_eeprom_byte_rd_wr/rtl/i2c_ctrl.v"
add_design "E:/FPGA_pro/Pango/PG2L100H/29_eeprom_byte_rd_wr/rtl/i2c_rw_data.v"
add_design "E:/FPGA_pro/Pango/PG2L100H/29_eeprom_byte_rd_wr/rtl/key_filter.v"
add_design "E:/FPGA_pro/Pango/PG2L100H/29_eeprom_byte_rd_wr/rtl/uart_tx.v"
add_constraint "E:/FPGA_pro/Pango/PG2L100H/29_eeprom_byte_rd_wr/pds_prj/eeprom_byte_rd_wr.fdc"
add_simulation "E:/FPGA_pro/Pango/PG2L100H/29_eeprom_byte_rd_wr/sim/M24LC64.v"
add_simulation "E:/FPGA_pro/Pango/PG2L100H/29_eeprom_byte_rd_wr/sim/tb_eeprom_byte_rd_wr.v"
add_simulation "E:/FPGA_pro/Pango/PG2L100H/29_eeprom_byte_rd_wr/rtl/eeprom_byte_rd_wr.v"
add_simulation "E:/FPGA_pro/Pango/PG2L100H/29_eeprom_byte_rd_wr/rtl/i2c_ctrl.v"
add_simulation "E:/FPGA_pro/Pango/PG2L100H/29_eeprom_byte_rd_wr/rtl/i2c_rw_data.v"
add_simulation "E:/FPGA_pro/Pango/PG2L100H/29_eeprom_byte_rd_wr/rtl/key_filter.v"
add_simulation "E:/FPGA_pro/Pango/PG2L100H/29_eeprom_byte_rd_wr/rtl/uart_tx.v"
add_design E:/FPGA_pro/Pango/PG2L100H/29_eeprom_byte_rd_wr/pds_prj/ipcore/fifo_data/fifo_data.idf
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module eeprom_byte_rd_wr
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
