#Generated by Fabric Compiler ( version 2025.2 <build 211867> ) at Sun Sep 27 17:33:38 2026

add_design "E:/code/PangoWork/Works/hdmi/ipcore/pll_50mhz/pll_50mhz.v" -library work -verilog
add_design "E:/code/PangoWork/Works/hdmi/Designs/drivers/iic/iic_master.v" -library work -verilog
add_design "E:/code/PangoWork/Works/hdmi/Designs/hardware/ms7200/ms7200_driver.v" -library work -verilog
add_design "E:/code/PangoWork/Works/hdmi/Designs/hardware/ms7200/ms7200_top.v" -library work -verilog
add_design "E:/code/PangoWork/Works/hdmi/Designs/hardware/ms7210/ms7210_driver.v" -library work -verilog
add_design "E:/code/PangoWork/Works/hdmi/Designs/hardware/ms7210/ms7210_top.v" -library work -verilog
add_design "E:/code/PangoWork/Works/hdmi/Designs/hdmi_loop_top.v" -library work -verilog
set_option -options {top_module	hdmi_loop_top} [get_filesets design_1]
set_option -options {fsm_compiler	true} [get_actions compile -of_objects [get_tasks syn_1]]
set_option max_threads 0
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
set_option -options { top_module {hdmi_loop_top}} [get_filesets design_1]
launch_tasks [get_tasks {syn_1}] -to_action compile
wait_on_tasks [get_tasks {syn_1}] -to_action compile
set_option max_threads 0
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
set_option -options { top_module {hdmi_loop_top}} [get_filesets design_1]
launch_tasks [get_tasks {syn_1}] -to_action compile
wait_on_tasks [get_tasks {syn_1}] -to_action compile
add_design "E:/code/PangoWork/Works/hdmi/ipcore/pll_50mhz/pll_50mhz.v" -library work -verilog
add_design "E:/code/PangoWork/Works/hdmi/Designs/drivers/iic/iic_master.v" -library work -verilog
add_design "E:/code/PangoWork/Works/hdmi/Designs/hardware/ms7200/ms7200_driver.v" -library work -verilog
add_design "E:/code/PangoWork/Works/hdmi/Designs/hardware/ms7200/ms7200_top.v" -library work -verilog
add_design "E:/code/PangoWork/Works/hdmi/Designs/hardware/ms7210/ms7210_driver.v" -library work -verilog
add_design "E:/code/PangoWork/Works/hdmi/Designs/hardware/ms7210/ms7210_top.v" -library work -verilog
add_design "E:/code/PangoWork/Works/hdmi/Designs/hardware/led/led.v" -library work -verilog
add_design "E:/code/PangoWork/Works/hdmi/Designs/hdmi_loop_top.v" -library work -verilog
set_option -options {top_module	hdmi_loop_top} [get_filesets design_1]
set_option -options {fsm_compiler	true} [get_actions compile -of_objects [get_tasks syn_1]]
set_option max_threads 0
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
set_option -options { top_module {hdmi_loop_top}} [get_filesets design_1]
launch_tasks [get_tasks {syn_1}] -to_action compile
wait_on_tasks [get_tasks {syn_1}] -to_action compile
add_design "E:/code/PangoWork/Works/hdmi/ipcore/pll_50mhz/pll_50mhz.v" -library work -verilog
add_design "E:/code/PangoWork/Works/hdmi/Designs/drivers/iic/iic_master.v" -library work -verilog
add_design "E:/code/PangoWork/Works/hdmi/Designs/hardware/ms7200/ms7200_driver.v" -library work -verilog
add_design "E:/code/PangoWork/Works/hdmi/Designs/hardware/ms7200/ms7200_top.v" -library work -verilog
add_design "E:/code/PangoWork/Works/hdmi/Designs/hardware/ms7210/ms7210_driver.v" -library work -verilog
add_design "E:/code/PangoWork/Works/hdmi/Designs/hardware/ms7210/ms7210_top.v" -library work -verilog
add_design "E:/code/PangoWork/Works/hdmi/Designs/hardware/led/led.v" -library work -verilog
add_design "E:/code/PangoWork/Works/hdmi/Designs/hdmi_loop_top.v" -library work -verilog
add_constraint "E:/code/PangoWork/Works/hdmi/Constraints/hdmi/hdmi_in.fdc"
add_constraint "E:/code/PangoWork/Works/hdmi/Constraints/hdmi/hdmi_out.fdc"
add_constraint "E:/code/PangoWork/Works/hdmi/Constraints/hdmi/ms7200.fdc"
add_constraint "E:/code/PangoWork/Works/hdmi/Constraints/hdmi/ms7210.fdc"
add_constraint "E:/code/PangoWork/Works/hdmi/Constraints/led/led.fdc"
add_constraint "E:/code/PangoWork/Works/hdmi/Constraints/system/system.fdc"
add_constraint "E:/code/PangoWork/Works/hdmi/Constraints/system/system_clk.fdc"
set_option {max_threads} {0}
set_option -options {top_module	hdmi_loop_top	top_library	work} [get_filesets design_1]
set_option max_threads 0
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
set_option -options { top_module {hdmi_loop_top}} [get_filesets design_1]
launch_tasks [get_tasks {syn_1}] -to_action compile
wait_on_tasks [get_tasks {syn_1}] -to_action compile
launch_tasks [get_tasks {syn_1}] -to_action synthesize
wait_on_tasks [get_tasks {syn_1}] -to_action synthesize
